name: Update Fake VLESS Node

on:
  schedule:
    - cron: '0 */3 * * *'  # هر 3 ساعت یکبار
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run update script
      run: python update_fake_node.py

    - name: Commit and Push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add grpc-server
        git commit -m "Add fake VLESS node with usage info" || echo "Nothing to commit"
        git push
