name: Update Fake V2Ray Node

on:
  schedule:
    - cron: "0 */3 * * *"  # هر 3 ساعت یکبار اجرا
  workflow_dispatch:       # اجرای دستی

jobs:
  update-fake-node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Run fake node updater script
        run: python update_fake_node.py

      - name: Commit and push changes with rebase and force push fallback
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add grpc-server
          git commit -m "🔁 Auto update fake node" || echo "No changes to commit"

          git fetch origin main
          if git rebase origin/main; then
            git push origin main
          else
            echo "Rebase failed, force pushing..."
            git rebase --abort || true
            git push --force origin main
          fi
